'use client';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import { Provider } from 'react-redux';
import store from './slice/index';

const inter = Kanit({ subsets: ['latin'], weight: '400' });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className="bg-red-300">
          <Navbar />
          {children}
        </body>
      </html>
    </Provider>
  );
}
