'use client';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import store from './slice/index';
import Navbar from './components/Navbar';

const inter = Kanit({ subsets: ['latin'], weight: '400' });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   document.querySelector('html')?.classList.add('dark');
  // }, []);
  return (
    <Provider store={store}>
      <html lang="en">
        <body
          className={`${inter.className} bg-[#222222] text-white mb-12 md:mb-0 h-screen overflow-hidden`}
        >
          {children}
        </body>
      </html>
    </Provider>
  );
}
